project:
  type: website
  output-dir: docs
  resources:
  - fonts/*.*
  - img/IMG_2950_wide.jpg

website:
  title: "ISCB46"
  cookie-consent:
    type: express
    style: headline
    policy-url: https://www.iscb2025.info/imprint-and-privacy-policy.html
    prefs-text: "Cookie Preferences & Privacy Policy"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Key Dates"
        href: key-dates.qmd
      - text: "About ISCB46"
        menu: 
        - text: "Committees"
          href: committees.qmd
      - text: "Conference information"
        menu: 
        - text: "Registration"
          href: registration.qmd
        - text: "Social Program"
          href: social.qmd
        - text: "Calls (archived)"
          href: calls.qmd
        - text: "Awards & Support"
        - text: "Best Poster & Presentation Awards"
          href: awards-contributions.qmd
        - text: "Student Conference Award (StCA)"
          href: awards-student.qmd
        - text: "Conference Attendance Support Program (CASP)"
          href: awards-casp.qmd
        # - href: venue.qmd
        #   text: "Conference venue"
        - text: "Policies"
        - href: imprint-and-privacy-policy.qmd
          text: "Privacy policy"
      - text: "Program"
        menu: 
         - text: "Pre-conference Courses"
           href: courses.qmd
         - text: "Invited Sessions"
           href: invited-sessions.qmd
         - text: "Mini-Symposia"
           href: mini-symposia.qmd
      - text: "About Basel"
        menu:
        - text: "Overview"
          href: about-basel.qmd
        - text: "Accommodation"
          href: accommodation.qmd
        - text: "Basel Card"
          href: basel-card.qmd
        - text: "Restaurants"
          href: restaurants.qmd
      - text: "FAQ"
        href: faq.qmd
      - text: "Sponsors"
        href: sponsors.qmd
  favicon: img/favicon.jpg


format:
  html:
    theme: 
    - zephyr-red.scss
    - custom.scss
    css: styles.css
    toc: true

