project:
  type: website
  output-dir: docs
  resources:
  - fonts/*.*
  - img/IMG_2950_wide.jpg

website:
  title: "ISCB46"
  cookie-consent:
    type: express
    style: headline
    policy-url: https://www.iscb2025.info/imprint-and-privacy-policy.html
    prefs-text: "Cookie Preferences & Privacy Policy"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Key Dates"
        href: key-dates.qmd
      - text: "About ISCB46"
        menu: 
        - text: "Committees"
          href: committees.qmd
      - text: "Conference information"
        menu: 
        - text: "Calls"
          href: calls.qmd
        # - href: venue.qmd
        #   text: "Conference venue"
        - href: imprint-and-privacy-policy.qmd
          text: "Privacy policy"
      # - text: "Program"
      #   menu: 
      #   - text: "TBD"
      - text: "About Basel"
        menu:
        - text: "Overview"
          href: about-basel.qmd
        - text: "Basel Card"
          href: basel-card.qmd
        - text: "Restaurants"
          href: restaurants.qmd
  favicon: img/favicon.jpg


format:
  html:
    theme: 
    - zephyr-red.scss
    - custom.scss
    css: styles.css
    toc: true

